version: 2.1
orbs:
    aws-ecr: circleci/aws-ecr@6.1.0
    aws-ecs: circleci/aws-ecs@0.0.8
workflows:
    build_and_push_image:
        jobs:
            - aws-ecr/build-and-push-image:
                dockerfile:'docker/php/Dockerfile'
                region: AWS_REGION
                account-url: AWS_ECR_ACCOUNT_URL
                repo: 'ci-deploytest'
                tag: "${CIRCLE_SHA1}"
            - aws-ecs/deploy-service-update:
                requires:
                    - aws-ecr/build-and-push-image
                family: 'test_task'
                cluster-name: 'cluster01'
                service-name: 'test_service'
                container-image-name-updates: 'container=app_container,tag=${CIRCLE_SHA1}'
